global:
  scrape_interval:     15s
  scrape_timeout: 2s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "nginx-exporter"
    scrape_interval: 5s
    static_configs:
    - targets: ["nginx-exporter:9113"]

  - job_name: 'phpfpm'
    scrape_interval: 5s
    static_configs:
      - targets: ['fpm-exporter:9253']
